In [0]:
from sklearn import tree

In [0]:
features = [[140, 1],[130, 1],[150, 0],[170, 0]]
labels = [0, 0, 1, 1]

In [0]:
clf = tree.DecisionTreeClassifier()
clf = clf.fit(features, labels)

In [14]:
print(clf.predict([[150, 0]]))

[1]


Visualization

In [0]:
import numpy as np
from sklearn.datasets import load_iris
from sklearn import tree

In [37]:
iris = load_iris()

print(iris.feature_names)
print(iris.target_names)

['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']
['setosa' 'versicolor' 'virginica']


In [38]:
print(iris.data[0])
print(iris.target[0])

[5.1 3.5 1.4 0.2]
0


In [0]:
test_idx = [0, 50, 100]

In [0]:
#training data
train_target = np.delete(iris.target, test_idx)
train_data = np.delete(iris.data, test_idx, axis=0)

In [0]:
#testing data
test_target = iris.target[test_idx]
test_data = iris.data[test_idx]

In [0]:
clf = tree.DecisionTreeClassifier()
clf = clf.fit(train_data, train_target)

In [44]:
print(test_target)

[0 1 2]


In [45]:
print(clf.predict(test_data))

[0 1 2]


In [0]:
#viz code
from sklearn.datasets import load_iris
from sklearn import tree

clf = tree.DecisionTreeClassifier()
iris = load_iris()

clf = clf.fit(iris.data, iris.target)
tree.export_graphviz(clf,out_file='tree.png')  

In [10]:
import Image

image = Image.open('tree.png')
image.show()

ModuleNotFoundError: ignored